name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Lint
      run: |
        go mod download
        go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
        PATH=$PATH:$HOME/go/bin golangci-lint run

    - name: Test
      run: |
          echo ${{ secrets.DevConfig }} > conf/dev.json
          ls -lh conf/dev.json
          go test -v .

    - name: Build
      run: |
        GO111MODULE=off go get github.com/swaggo/swag/cmd/swag
        export PATH=$PATH:$HOME/go/bin
        swag init -g web/router.go
